[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Usa el Python de Netlify (con headers) y una versión Node estable
  PYTHON_VERSION = "3.11.9"
  NODE_VERSION   = "22.20.0"

  # Evita que mise “imponga” su Python recortado
  MISE_SKIP = "1"

  # Pide a pip que use wheel para pycairo (evita compilar)
  PIP_ONLY_BINARY = "pycairo"
