[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Usa el Python de Netlify (con headers) y evita el Python "stripped" de mise
  PYTHON_VERSION = "3.11.9"
  MISE_SKIP = "1"

  # (Opcional pero recomendable) fija Node para evitar sorpresas
  NODE_VERSION = "22.20.0"