[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Desactiva mise en el build de Netlify
  MISE_SKIP = "1"

  # Fija Node (y, por si algún script toca Python, fíltralo a una versión estable)
  NODE_VERSION   = "22.20.0"
  PYTHON_VERSION = "3.11.9"
